// Copyright 2026 The etcd Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package transport

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"go.uber.org/zap/zaptest"
)

// fakeCertPoolProvider is a thread-safe CertPoolProvider used in tests.
type fakeCertPoolProvider struct {
	pool atomic.Pointer[x509.CertPool]
}

func newFakeCertPoolProvider(pool *x509.CertPool) *fakeCertPoolProvider {
	p := &fakeCertPoolProvider{}
	p.pool.Store(pool)
	return p
}

func (p *fakeCertPoolProvider) GetCertPool() *x509.CertPool { return p.pool.Load() }

func (p *fakeCertPoolProvider) Set(pool *x509.CertPool) { p.pool.Store(pool) }

// errCertPoolProvider always returns nil to simulate a misconfigured provider.
type errCertPoolProvider struct{}

func (errCertPoolProvider) GetCertPool() *x509.CertPool { return nil }

// countingProvider wraps a pool and counts GetCertPool calls.
type countingProvider struct {
	pool  *x509.CertPool
	calls *atomic.Int64
}

func (c *countingProvider) GetCertPool() *x509.CertPool {
	c.calls.Add(1)
	return c.pool
}

// testCA is a self-signed CA with a private key, used to sign leaf certs in tests.
type testCA struct {
	Cert *x509.Certificate
	DER  []byte
	Key  *ecdsa.PrivateKey
}

func newTestCA(t *testing.T, commonName string) *testCA {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P521(), rand.Reader)
	require.NoError(t, err)
	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	require.NoError(t, err)
	tmpl := x509.Certificate{
		SerialNumber:          serial,
		Subject:               pkix.Name{CommonName: commonName},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(24 * time.Hour),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
		IsCA:                  true,
	}
	der, err := x509.CreateCertificate(rand.Reader, &tmpl, &tmpl, &key.PublicKey, key)
	require.NoError(t, err)
	cert, err := x509.ParseCertificate(der)
	require.NoError(t, err)
	return &testCA{Cert: cert, DER: der, Key: key}
}

func (ca *testCA) PEM() []byte {
	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: ca.DER})
}

func (ca *testCA) Pool() *x509.CertPool {
	pool := x509.NewCertPool()
	pool.AddCert(ca.Cert)
	return pool
}

// leafMaterial is a self-signed-mimicking cert with its private key, used to
// drive TLSInfo. It is generated by a CA so it chains up to the CA pool.
type leafMaterial struct {
	Cert    tls.Certificate
	CertPEM []byte
	KeyPEM  []byte
}

func (ca *testCA) signLeaf(t *testing.T, commonName string, hosts []string) leafMaterial {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P521(), rand.Reader)
	require.NoError(t, err)
	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	require.NoError(t, err)
	tmpl := x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: commonName},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(24 * time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
	}
	for _, h := range hosts {
		if ip := net.ParseIP(h); ip != nil {
			tmpl.IPAddresses = append(tmpl.IPAddresses, ip)
		} else {
			tmpl.DNSNames = append(tmpl.DNSNames, h)
		}
	}
	der, err := x509.CreateCertificate(rand.Reader, &tmpl, ca.Cert, &key.PublicKey, ca.Key)
	require.NoError(t, err)
	keyDER, err := x509.MarshalECPrivateKey(key)
	require.NoError(t, err)
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER})
	pair, err := tls.X509KeyPair(certPEM, keyPEM)
	require.NoError(t, err)
	return leafMaterial{Cert: pair, CertPEM: certPEM, KeyPEM: keyPEM}
}

// writeTLSInfo saves cert + key + ca to a temp dir and returns paths.
// If extraCAs is provided, they are appended to the ca file as a bundle.
func writeTLSInfo(t *testing.T, leaf leafMaterial, ca *testCA, extraCAs ...*testCA) (certPath, keyPath, caPath string) {
	t.Helper()
	dir := t.TempDir()
	certPath = filepath.Join(dir, "leaf.crt")
	keyPath = filepath.Join(dir, "leaf.key")
	caPath = filepath.Join(dir, "ca.crt")
	require.NoError(t, os.WriteFile(certPath, leaf.CertPEM, 0o600))
	require.NoError(t, os.WriteFile(keyPath, leaf.KeyPEM, 0o600))
	bundle := append([]byte{}, ca.PEM()...)
	for _, extra := range extraCAs {
		bundle = append(bundle, extra.PEM()...)
	}
	require.NoError(t, os.WriteFile(caPath, bundle, 0o600))
	return certPath, keyPath, caPath
}

// startServer builds a TLS listener from info and returns the listener and
// the matching address. The listener is closed on test cleanup. A goroutine
// drains Accept and explicitly performs the server-side handshake so the
// dial on the client side completes.
func startServer(t *testing.T, info *TLSInfo) (net.Listener, string) {
	t.Helper()
	cfg, err := info.ServerConfig()
	require.NoError(t, err)
	ln, err := tls.Listen("tcp", "127.0.0.1:0", cfg)
	require.NoError(t, err)
	done := make(chan struct{})
	go func() {
		defer close(done)
		for {
			conn, err := ln.Accept()
			if err != nil {
				return
			}
			tc, ok := conn.(*tls.Conn)
			if ok {
				_ = tc.Handshake()
			}
			_ = conn.Close()
		}
	}()
	t.Cleanup(func() {
		_ = ln.Close()
		<-done
	})
	return ln, ln.Addr().String()
}

// dialClient connects a client whose TrustRoots come from the provider.
func dialClient(t *testing.T, info *TLSInfo, addr string) error {
	t.Helper()
	cfg, err := info.ClientConfig()
	require.NoError(t, err)
	cfg.ServerName = "localhost"
	conn, err := tls.Dial("tcp", addr, cfg)
	if err != nil {
		return err
	}
	defer conn.Close()
	return conn.Handshake()
}


// TestSetDynamicTrustRoots_NilPreservesServerBehavior verifies that with no
// provider, ServerConfig does not install GetConfigForClient.
func TestSetDynamicTrustRoots_NilPreservesServerBehavior(t *testing.T) {
	ca1 := newTestCA(t, "ca1")
	leaf := ca1.signLeaf(t, "server", []string{"127.0.0.1"})
	certPath, keyPath, caPath := writeTLSInfo(t, leaf, ca1)

	info := &TLSInfo{
		CertFile:       certPath,
		KeyFile:        keyPath,
		TrustedCAFile:  caPath,
		ClientCertAuth: true,
		Logger:         zaptest.NewLogger(t),
	}
	cfg, err := info.ServerConfig()
	require.NoError(t, err)
	require.Nil(t, cfg.GetConfigForClient, "server config should not install GetConfigForClient when no provider is set")

	clientCfg, err := info.ClientConfig()
	require.NoError(t, err)
	require.False(t, clientCfg.InsecureSkipVerify, "client config should not enable InsecureSkipVerify when no provider is set")
}

// TestServerConfig_DynamicRootCAsAcceptsNewClientCAOnNewHandshake proves that
// when the provider rotates, the server accepts a new client cert under the
// new CA without restarting.
func TestServerConfig_DynamicRootCAsAcceptsNewClientCAOnNewHandshake(t *testing.T) {
	ca1 := newTestCA(t, "ca1")
	ca2 := newTestCA(t, "ca2")

	// Server's leaves are signed by CA1 (used only so the server can present a
	// cert chain the client can trust via the static CA file on the client).
	serverLeaf := ca1.signLeaf(t, "server", []string{"127.0.0.1", "localhost"})
	srvCertPath, srvKeyPath, _ := writeTLSInfo(t, serverLeaf, ca1)

	var calls atomic.Int64
	provider := &countingProvider{pool: ca1.Pool(), calls: &calls}
	serverInfo := &TLSInfo{
		CertFile:       srvCertPath,
		KeyFile:        srvKeyPath,
		TrustedCAFile:  "", // not used: provider drives trust
		ClientCertAuth: true,
		Logger:         zaptest.NewLogger(t),
	}
	serverInfo.SetDynamicTrustRoots(provider)
	_, addr := startServer(t, serverInfo)

	// Client under CA1 connects. The client uses CA1+CA2 as a static bundle so
	// it can verify the server (CA1-signed) regardless of which CA2 leaf is used.
	client1Leaf := ca1.signLeaf(t, "client1", []string{"127.0.0.1", "localhost"})
	c1Cert, c1Key, c1CA := writeTLSInfo(t, client1Leaf, ca1, ca2)
	client1Info := &TLSInfo{
		CertFile:      c1Cert,
		KeyFile:       c1Key,
		TrustedCAFile: c1CA,
		ServerName:    "localhost",
		Logger:        zaptest.NewLogger(t),
	}
	require.NoError(t, dialClient(t, client1Info, addr))
	firstCalls := calls.Load()
	require.GreaterOrEqual(t, firstCalls, int64(1), "provider should be consulted at least once")

	// Rotate provider to CA2 and dial with a client leaf under CA2.
	provider.pool = ca2.Pool()
	client2Leaf := ca2.signLeaf(t, "client2", []string{"127.0.0.1", "localhost"})
	c2Cert, c2Key, c2CA := writeTLSInfo(t, client2Leaf, ca2, ca1)
	client2Info := &TLSInfo{
		CertFile:      c2Cert,
		KeyFile:       c2Key,
		TrustedCAFile: c2CA,
		ServerName:    "localhost",
		Logger:        zaptest.NewLogger(t),
	}
	err := dialClient(t, client2Info, addr)
	require.NoError(t, err, "client under CA2 should be accepted after rotation")
}

// TestClientConfig_DynamicRootCAsAcceptsNewServerCAOnNewHandshake proves that
// a client using a dynamic provider accepts a rotated server cert.
func TestClientConfig_DynamicRootCAsAcceptsNewServerCAOnNewHandshake(t *testing.T) {
	ca1 := newTestCA(t, "ca1")
	ca2 := newTestCA(t, "ca2")

	// Build a server with CA1-signed leaf.
	server1Leaf := ca1.signLeaf(t, "server1", []string{"127.0.0.1", "localhost"})
	srvCert, srvKey, _ := writeTLSInfo(t, server1Leaf, ca1)
	serverInfo := &TLSInfo{
		CertFile:       srvCert,
		KeyFile:        srvKey,
		ClientCertAuth: true,
		TrustedCAFile:  "",
		Logger:         zaptest.NewLogger(t),
	}

	// Client uses dynamic provider starting at CA1.
	provider := newFakeCertPoolProvider(ca1.Pool())
	clientLeaf := ca1.signLeaf(t, "client", []string{"127.0.0.1", "localhost"})
	cCert, cKey, _ := writeTLSInfo(t, clientLeaf, ca1)
	clientInfo := &TLSInfo{
		CertFile:      cCert,
		KeyFile:       cKey,
		ServerName:    "localhost",
		Logger:        zaptest.NewLogger(t),
	}
	clientInfo.SetDynamicTrustRoots(provider)

	// Start server under CA1, dial with provider at CA1.
	_, addr := startServer(t, serverInfo)
	require.NoError(t, dialClient(t, clientInfo, addr))

	// Rotate provider to CA2; rebuild server under CA2.
	provider.Set(ca2.Pool())
	server2Leaf := ca2.signLeaf(t, "server2", []string{"127.0.0.1", "localhost"})
	srvCert2, srvKey2, _ := writeTLSInfo(t, server2Leaf, ca2)
	serverInfo2 := &TLSInfo{
		CertFile:       srvCert2,
		KeyFile:        srvKey2,
		ClientCertAuth: true,
		TrustedCAFile:  "",
		Logger:         zaptest.NewLogger(t),
	}
	_, addr2 := startServer(t, serverInfo2)
	require.NoError(t, dialClient(t, clientInfo, addr2), "client under CA2 trust should accept server under CA2")
}

// TestDynamicRootCAs_NilProviderReturnsError confirms that a provider returning
// nil causes a handshake failure.
func TestDynamicRootCAs_NilProviderReturnsError(t *testing.T) {
	ca1 := newTestCA(t, "ca1")

	// Server with CA1-signed leaf.
	serverLeaf := ca1.signLeaf(t, "server", []string{"127.0.0.1", "localhost"})
	srvCert, srvKey, _ := writeTLSInfo(t, serverLeaf, ca1)
	serverInfo := &TLSInfo{
		CertFile:       srvCert,
		KeyFile:        srvKey,
		ClientCertAuth: true,
		TrustedCAFile:  "",
		Logger:         zaptest.NewLogger(t),
	}
	_, addr := startServer(t, serverInfo)

	// Client with errCertPoolProvider.
	clientLeaf := ca1.signLeaf(t, "client", []string{"127.0.0.1", "localhost"})
	cCert, cKey, _ := writeTLSInfo(t, clientLeaf, ca1)
	clientInfo := &TLSInfo{
		CertFile:      cCert,
		KeyFile:       cKey,
		ServerName:    "localhost",
		Logger:        zaptest.NewLogger(t),
	}
	clientInfo.SetDynamicTrustRoots(errCertPoolProvider{})

	err := dialClient(t, clientInfo, addr)
	require.Error(t, err, "handshake must fail when provider returns nil pool")
	require.Contains(t, err.Error(), "nil cert pool")
}

// TestDynamicRootCAs_ConcurrentHandshakes exercises many concurrent handshakes
// against the same provider-backed server and ensures no race is observed.
func TestDynamicRootCAs_ConcurrentHandshakes(t *testing.T) {
	ca1 := newTestCA(t, "ca1")
	var calls atomic.Int64
	provider := &countingProvider{pool: ca1.Pool(), calls: &calls}

	serverLeaf := ca1.signLeaf(t, "server", []string{"127.0.0.1", "localhost"})
	srvCert, srvKey, _ := writeTLSInfo(t, serverLeaf, ca1)
	serverInfo := &TLSInfo{
		CertFile:       srvCert,
		KeyFile:        srvKey,
		ClientCertAuth: true,
		TrustedCAFile:  "",
		Logger:         zaptest.NewLogger(t),
	}
	serverInfo.SetDynamicTrustRoots(provider)
	_, addr := startServer(t, serverInfo)

	const n = 16
	clientLeaf := ca1.signLeaf(t, "client", []string{"127.0.0.1", "localhost"})
	cCert, cKey, cCA := writeTLSInfo(t, clientLeaf, ca1)
	clientInfo := &TLSInfo{
		CertFile:      cCert,
		KeyFile:       cKey,
		TrustedCAFile: cCA,
		ServerName:    "localhost",
		Logger:        zaptest.NewLogger(t),
	}

	var wg sync.WaitGroup
	wg.Add(n)
	for i := 0; i < n; i++ {
		go func() {
			defer wg.Done()
			if err := dialClient(t, clientInfo, addr); err != nil {
				t.Errorf("concurrent dial: %v", err)
			}
		}()
	}
	wg.Wait()
	require.GreaterOrEqual(t, calls.Load(), int64(n), "provider should be consulted at least once per handshake")
}

// TestDynamicRootCAs_DoesNotBreakExistingConnection asserts that a connection
// already in use survives a trust-root rotation; only new handshakes pick up
// the new pool.
func TestDynamicRootCAs_DoesNotBreakExistingConnection(t *testing.T) {
	ca1 := newTestCA(t, "ca1")
	ca2 := newTestCA(t, "ca2")
	provider := newFakeCertPoolProvider(ca1.Pool())

	serverLeaf := ca1.signLeaf(t, "server", []string{"127.0.0.1", "localhost"})
	srvCert, srvKey, _ := writeTLSInfo(t, serverLeaf, ca1)
	serverInfo := &TLSInfo{
		CertFile:       srvCert,
		KeyFile:        srvKey,
		ClientCertAuth: true,
		TrustedCAFile:  "",
		Logger:         zaptest.NewLogger(t),
	}
	serverInfo.SetDynamicTrustRoots(provider)
	_, addr := startServer(t, serverInfo)

	// Open a connection under CA1 and complete the handshake.
	clientLeaf := ca1.signLeaf(t, "client", []string{"127.0.0.1", "localhost"})
	cCert, cKey, cCA := writeTLSInfo(t, clientLeaf, ca1)
	clientCfg, err := (&TLSInfo{
		CertFile:      cCert,
		KeyFile:       cKey,
		TrustedCAFile: cCA,
		ServerName:    "localhost",
		Logger:        zaptest.NewLogger(t),
	}).ClientConfig()
	require.NoError(t, err)
	conn, err := tls.Dial("tcp", addr, clientCfg)
	require.NoError(t, err)
	defer conn.Close()

	// Rotate provider to CA2. Existing conn must remain usable.
	provider.Set(ca2.Pool())
	_, err = conn.Write([]byte("ping"))
	require.NoError(t, err, "established connection should remain usable after rotation")
}

// TestDynamicRootCAs_PreservesHostnameVerification ensures that when a
// provider is configured, mismatched ServerName still fails the handshake.
func TestDynamicRootCAs_PreservesHostnameVerification(t *testing.T) {
	ca1 := newTestCA(t, "ca1")
	provider := newFakeCertPoolProvider(ca1.Pool())

	serverLeaf := ca1.signLeaf(t, "server", []string{"127.0.0.1", "localhost"})
	srvCert, srvKey, _ := writeTLSInfo(t, serverLeaf, ca1)
	serverInfo := &TLSInfo{
		CertFile:       srvCert,
		KeyFile:        srvKey,
		ClientCertAuth: true,
		TrustedCAFile:  "",
		Logger:         zaptest.NewLogger(t),
	}
	serverInfo.SetDynamicTrustRoots(provider)
	_, addr := startServer(t, serverInfo)

	// Client presents a CA1-signed leaf but expects ServerName "wrong-host".
	clientLeaf := ca1.signLeaf(t, "client", []string{"127.0.0.1", "localhost"})
	cCert, cKey, cCA := writeTLSInfo(t, clientLeaf, ca1)
	clientCfg, err := (&TLSInfo{
		CertFile:      cCert,
		KeyFile:       cKey,
		TrustedCAFile: cCA,
		ServerName:    "wrong-host",
		Logger:        zaptest.NewLogger(t),
	}).ClientConfig()
	require.NoError(t, err)
	conn, err := tls.Dial("tcp", addr, clientCfg)
	if err == nil {
		_ = conn.Close()
		err = conn.Handshake()
	}
	require.Error(t, err, "mismatched ServerName should fail handshake even with dynamic provider")
}

// TestDynamicRootCAs_PreservesAllowedCN asserts that the AllowedCNs check
// (configured via baseConfig) is preserved when the trust-root provider is
// configured. The server's tc.Handshake() returns the rejection error; this
// is the authoritative side because the stdlib ClientHello exchange is
// driven by the server, and the rejection manifests there first.
func TestDynamicRootCAs_PreservesAllowedCN(t *testing.T) {
	ca1 := newTestCA(t, "ca1")
	provider := newFakeCertPoolProvider(ca1.Pool())

	serverLeaf := ca1.signLeaf(t, "server", []string{"127.0.0.1", "localhost"})
	srvCert, srvKey, _ := writeTLSInfo(t, serverLeaf, ca1)
	serverInfo := &TLSInfo{
		CertFile:       srvCert,
		KeyFile:        srvKey,
		ClientCertAuth: true,
		TrustedCAFile:  "",
		AllowedCNs:     []string{"allowed-client"},
		Logger:         zaptest.NewLogger(t),
	}
	serverInfo.SetDynamicTrustRoots(provider)

	// Build the server config and listener manually so we can install a
	// accept loop that observes the handshake error from the server side.
	cfg, err := serverInfo.ServerConfig()
	require.NoError(t, err)
	ln, err := tls.Listen("tcp", "127.0.0.1:0", cfg)
	require.NoError(t, err)
	t.Cleanup(func() { _ = ln.Close() })
	addr := ln.Addr().String()

	handshakeErrs := make(chan error, 1)
	done := make(chan struct{})
	go func() {
		defer close(done)
		for {
			conn, err := ln.Accept()
			if err != nil {
				return
			}
			tc := conn.(*tls.Conn)
			handshakeErrs <- tc.Handshake()
			_ = conn.Close()
		}
	}()

	// Client presents a CA1-signed leaf whose CN "not-allowed" is not in
	// AllowedCNs. The client config does NOT bypass AllowedCN; this is a
	// straight mTLS attempt that should be rejected by the server.
	clientLeaf := ca1.signLeaf(t, "not-allowed", []string{"127.0.0.1", "localhost"})
	cCert, cKey, cCA := writeTLSInfo(t, clientLeaf, ca1)
	clientCfg, err := (&TLSInfo{
		CertFile:      cCert,
		KeyFile:       cKey,
		TrustedCAFile: cCA,
		ServerName:    "localhost",
		Logger:        zaptest.NewLogger(t),
	}).ClientConfig()
	require.NoError(t, err)

	// Force the handshake to drive the server-side AllowedCN check.
	_, dialErr := tls.Dial("tcp", addr, clientCfg)
	_ = dialErr // client-side alert propagation is a separate concern.

	select {
	case herr := <-handshakeErrs:
		require.Error(t, herr, "server-side Handshake should reject client with disallowed CN")
		require.Contains(t, herr.Error(), "client certificate authentication failed")
	case <-time.After(2 * time.Second):
		t.Fatal("timed out waiting for server to process the connection")
	}
}
